#!/bin/sh
set -eu

./env

echo 'Start maven build'
./mvnw package -DskipTests
echo 'Finish maven build'

echo 'Start docker build'
docker-compose -f docker-compose.yml -f docker-compose.dev.yml build "$@"
echo 'Finish docker build'
