#!/bin/sh
set -eu

./env

echo 'Start load Google Sheets data'
python3 storage/postgres/loadDataFromGoogleSheets.py
echo 'Finish load Google Sheets data'

echo 'Start maven build'
./mvnw package -DskipTests
echo 'Finish maven build'

echo 'Start docker build'
docker-compose -f docker-compose.yml -f docker-compose.dev.yml build "$@"
echo 'Finish docker build'
