version: "2.4"
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
    volumes:
      - ./storage/rabbitmq/data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    image: postgis/postgis:10-3.2
    restart: always
    volumes:
      - ./storage/postgres/initdb/init_foodsharing_db.sql:/docker-entrypoint-initdb.d/init_schema.sql
      - ./storage/postgres/data:/var/lib/postgresql/data
    environment:
      PGUSER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_NAME:-foodsharing}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-postgres}
    healthcheck:
      test: pg_isready
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  nginx:
    image: nginx:stable
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      config:
        condition: service_healthy
      parser:
        condition: service_healthy
      analyzer:
        condition: service_healthy
      ibot:
        condition: service_healthy
      tg-bot:
        condition: service_healthy
      vk-bot:
        condition: service_healthy

  config:
    image: rassafel/foodsharing-config
    restart: always
    volumes:
      - ./config-service/src/main/resources/shared:/app/shared

  parser:
    image: rassafel/foodsharing-vk-parser
    restart: unless-stopped
    environment:
      CALLBACK_URL: $CALLBACK_URL
      PARSER_USERNAME: $PARSER_USERNAME

      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASS: ${RABBITMQ_PASS:-guest}

      POSTGRES_DB: ${POSTGRES_DB:-foodsharing}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASS: ${POSTGRES_PASS:-postgres}
    depends_on:
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  analyzer:
    image: rassafel/foodsharing-analyzer
    restart: unless-stopped
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASS: ${RABBITMQ_PASS:-guest}

      POSTGRES_DB: ${POSTGRES_DB:-foodsharing}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASS: ${POSTGRES_PASS:-postgres}
    depends_on:
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  ibot:
    image: rassafel/foodsharing-ibot
    restart: unless-stopped
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASS: ${RABBITMQ_PASS:-guest}

      POSTGRES_DB: ${POSTGRES_DB:-foodsharing}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASS: ${POSTGRES_PASS:-postgres}
    depends_on:
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  tg-bot:
    image: rassafel/foodsharing-tg-bot
    restart: unless-stopped
    environment:
      TG_BOT_WEB_HOOK_PATH: $TG_BOT_WEB_HOOK_PATH
      TG_BOT_USERNAME: $BOT_USERNAME
      TG_BOT_TOKEN: $TG_BOT_TOKEN

      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASS: ${RABBITMQ_PASS:-guest}

      POSTGRES_DB: ${POSTGRES_DB:-foodsharing}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASS: ${POSTGRES_PASS:-postgres}
    volumes:
      - ./bots/session-starter/src/main/resources/templates:/app/templates
    depends_on:
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  vk-bot:
    image: rassafel/foodsharing-vk-bot
    restart: unless-stopped
    environment:
      VK_BOT_GROUP_ID: $VK_BOT_GROUP_ID
      VK_BOT_ACCESS_TOKEN: $VK_BOT_ACCESS_TOKEN
      VK_CONFIRM_CODE: $VK_CONFIRM_CODE

      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASS: ${RABBITMQ_PASS:-guest}

      POSTGRES_DB: ${POSTGRES_DB:-foodsharing}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASS: ${POSTGRES_PASS:-postgres}
    volumes:
      - ./bots/session-starter/src/main/resources/templates:/app/templates
    depends_on:
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  ad:
    image: rassafel/foodsharing-ad
    restart: unless-stopped
    environment:
      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASS: ${RABBITMQ_PASS:-guest}
    depends_on:
      config:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
