version: "2.4"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"

  postgres:
    image: postgis/postgis:10-3.2-alpine
    ports:
      - "5432:5432"

  nginx:
    image: nginx:stable-alpine

  config:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    ports:
      - "8888:80"

  parser:
    build:
      context: ./parsers/vk-parser/webhook-impl
      dockerfile: Dockerfile
    ports:
      - "8000:80"

  analyzer:
    build:
      context: ./analyzer/impl
      dockerfile: Dockerfile
    ports:
      - "8010:80"

  ibot:
    build:
      context: ./bots/ibot/impl
      dockerfile: Dockerfile
    ports:
      - "8020:80"

  tg-bot:
    build:
      context: ./bots/tg-bot
      dockerfile: Dockerfile
    ports:
      - "8030:80"

  vk-bot:
    build:
      context: ./bots/vk-bot
      dockerfile: Dockerfile
    ports:
      - "8040:80"

  ad:
    build:
      context: ./ad/impl
      dockerfile: Dockerfile
    ports:
      - "8050:80"
