version: "3.4"
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    # volumes:
    #   - "./storage/rabbitmq/data:/var/lib/rabbitmq"
    #   - "./storage/rabbitmq/myrabbit.conf:/etc/rabbitmq/rabbitmq.config"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres:
    image: postgres:10
    restart: always
    ports:
      - "5432:5432"
    # volumes:
    #   - "./storage/postgres/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: foodsharing
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  config:
    image: rassafel/foodsharing-config
    restart: always
    environment:
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
    ports:
      - "8888:8888"
    healthcheck:
      test: curl -sS http://localhost:8888/actuator/health || echo 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  parser:
    image: rassafel/foodsharing-vk-parser
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      PARSER_TOKEN: $PARSER_TOKEN
      PARSER_APP_ID: $PARSER_APP_ID
    depends_on:
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: curl -sS http://localhost:8000/actuator/health || echo 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  analyzer:
    image: rassafel/foodsharing-analyzer
    restart: on-failure
    ports:
      - 8010:8010
    depends_on:
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
#    healthcheck:
#      test: curl -sS http://localhost:8010/actuator/health || echo 1
#      interval: 30s
#      timeout: 5s
#      retries: 5
#      start_period: 30s

  ibot:
    image: rassafel/foodsharing-ibot
    restart: on-failure
    ports:
      - 8020:8020
    depends_on:
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: curl -sS http://localhost:8020/actuator/health || echo 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  tg-bot:
    image: rassafel/foodsharing-tg-bot
    restart: on-failure
    ports:
      - 8030:8030
    environment:
      TELEGRAM_TOKEN: N/A
    depends_on:
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: curl -sS http://localhost:8030/actuator/health || echo 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  vk-bot:
    image: rassafel/foodsharing-vk-bot
    restart: on-failure
    ports:
      - 8040:8040
    environment:
      VKONTAKTE_TOKEN: N/A
      VKONTAKTE_GROUP_ID: N/A
    depends_on:
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: curl -sS http://localhost:8040/actuator/health || echo 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
