version: "3.4"
services:
  rabbitmq:
    image: rabbitmq:3-alpine

  postgres:
    image: postgres:10-alpine

  config:
    build:
      context: ./config-service
      dockerfile: Dockerfile

  parser:
    build:
      context: ./parsers/vk-parser
      dockerfile: Dockerfile
    restart: "no"

  analyzer:
    build:
      context: ./analyzer/impl
      dockerfile: Dockerfile
    restart: "no"

  ibot:
    build:
      context: ./ibot/impl
      dockerfile: Dockerfile
    restart: "no"

  tg-bot:
    build:
      context: ./bots/tg-bot
      dockerfile: Dockerfile
    restart: "no"

  vk-bot:
    build:
      context: ./bots/vk-bot
      dockerfile: Dockerfile
    restart: "no"
