version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-alpine

  postgres:
    image: postgres:10-alpine

  config:
    build:
      context: ./config-service
      dockerfile: Dockerfile

  parser:
    build:
      context: ./parser
      dockerfile: Dockerfile
    restart: "no"

  analyzer:
    build:
      context: ./analyzer/impl
      dockerfile: Dockerfile
    restart: "no"

  ibot:
    build:
      context: ./ibot
      dockerfile: Dockerfile
    restart: "no"

  tg-bot:
    build:
      context: ./tg-bot
      dockerfile: Dockerfile
    restart: "no"

  vk-bot:
    build:
      context: ./vk-bot
      dockerfile: Dockerfile
    restart: "no"
