version: "3.4"
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./storage/rabbitmq/data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASS
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres:
    image: postgis/postgis:10-3.2
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgres/initdb:/docker-entrypoint-initdb.d
      - ./storage/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASS
    healthcheck:
      test: pg_isready
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  config:
    image: rassafel/foodsharing-config
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./config-service/src/main/resources/shared:/app/shared

  parser:
    image: rassafel/foodsharing-vk-parser
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASS: $DATABASE_PASS

      RABBITMQ_USER: $RABBITMQ_USER
      RABBITMQ_PASS: $RABBITMQ_PASS

      VK_PARSER_TOKEN: $VK_PARSER_TOKEN
      VK_PARSER_APP_ID: $VK_PARSER_APP_ID
    depends_on:
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  analyzer:
    image: rassafel/foodsharing-analyzer
    restart: on-failure
    ports:
      - "8010:8010"
    environment:
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASS: $DATABASE_PASS

      RABBITMQ_USER: $RABBITMQ_USER
      RABBITMQ_PASS: $RABBITMQ_PASS
    depends_on:
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  ibot:
    image: rassafel/foodsharing-ibot
    restart: on-failure
    ports:
      - "8020:8020"
    environment:
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASS: $DATABASE_PASS

      RABBITMQ_USER: $RABBITMQ_USER
      RABBITMQ_PASS: $RABBITMQ_PASS
    depends_on:
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  tg-bot:
    image: rassafel/foodsharing-tg-bot
    restart: on-failure
    ports:
      - "8030:8030"
    environment:
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASS: $DATABASE_PASS

      RABBITMQ_USER: $RABBITMQ_USER
      RABBITMQ_PASS: $RABBITMQ_PASS

      TG_BOT_WEB_HOOK_PATH: $TG_BOT_WEB_HOOK_PATH
      TG_BOT_USERNAME: $TG_BOT_USERNAME
      TG_BOT_TOKEN: $TG_BOT_TOKEN
    depends_on:
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  vk-bot:
    image: rassafel/foodsharing-vk-bot
    restart: on-failure
    ports:
      - "8040:8040"
    environment:
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASS: $DATABASE_PASS

      RABBITMQ_USER: $RABBITMQ_USER
      RABBITMQ_PASS: $RABBITMQ_PASS

      VK_BOT_GROUP_ID: $VK_BOT_GROUP_ID
      VK_BOT_ACCESS_TOKEN: $VK_BOT_ACCESS_TOKEN
    depends_on:
      config:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
