#!/bin/sh

echo 'Start building'
./build
if [ $? -ne 0 ]; then
    exit $?
fi
echo 'Finish building'

echo 'Start load environment variables'
./env
echo 'Finish load environment variables'

echo 'Docker run'
docker-compose up --build "$@"
