#!/bin/sh

MODULES="analyzer"

GENERATED="generated"

for MODULE in ${MODULES}; do
    touch "$MODULE/$GENERATED/__init__.py"
    mkdir -p "$MODULE/$GENERATED/platform"
    cp -rf "platform/python/." "$MODULE/$GENERATED/platform/"
done
