server:
  port: ${SERVER_PORT:8020}
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    exchangeName: post-ready-exchange
    queueName: post.ready.main

  datasource:
    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate

  application:
    name: ibot
