tg:
  bot:
    webHookPath: ${TG_BOT_WEB_HOOK_PATH}
    username: ${TG_BOT_USERNAME}
    token: ${TG_BOT_TOKEN}
bot:
  session:
    messenger:
      maxQueryCountPerTime: 1
      maxQuerySizeInBatch: 30
