server:
  port: ${SERVER_PORT:8000}
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    exchangeName: post-raw-exchange

  datasource:
    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

  application:
    name: vk-parser

vk:
  parser:
    token: ${VK_PARSER_TOKEN}
    app.id: ${VK_PARSER_APP_ID}
