spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/foodsharing
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate

server:
  tomcat:
    port-header: X-Forwarded-Port
    remote-ip-header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto
    remoteip: X-Real-IP
