spring:
  rabbitmq:
    exchangeName: post-ready-exchange
    queueName: post.ready.tg

tg:
  bot:
    webHookPath: ${TG_BOT_WEB_HOOK_PATH}
    username: ${TG_BOT_USERNAME}
    token: ${TG_BOT_TOKEN}
