spring:
  rabbitmq:
    ready-post:
      queue: post.ready.tg
      dlq: post.ready.dlq.tg
    ad-post:
      queue: post.ad.tg
      dlq: post.ad.dlq.tg

    tg-bot-callback:
      queue: callback.tg.bot.current
      dlq: callback.tg.bot.dlq.current
  liquibase:
    contexts: tg-bot,data

tg:
  bot:
    webHookPath: ${TG_BOT_WEB_HOOK_PATH}
    username: ${TG_BOT_USERNAME:GetFoodBot}
    token: ${TG_BOT_TOKEN}
