spring:
  rabbitmq:
    exchangeName: post-ready-exchange
    queueName: post.ready.tg
  liquibase:
    contexts: tg-bot,data

tg:
  bot:
    webHookPath: ${TG_BOT_WEB_HOOK_PATH}
    username: ${TG_BOT_USERNAME}
    token: ${TG_BOT_TOKEN}
