spring:
  rabbitmq:
    ready-post:
      queue: post.ready.tg
      dlq: post.ready.dlq.tg
    ad-post:
      queue: post.ad.tg
      dlq: post.ad.dlq.tg
  liquibase:
    contexts: tg-bot,data

tg:
  bot:
    webHookPath: ${TG_BOT_WEB_HOOK_PATH}
    username: ${TG_BOT_USERNAME}
    token: ${TG_BOT_TOKEN}
