spring:
  rabbitmq:
    exchangeName: post-ready-exchange
    queueName: post.ready.vk
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect

vk:
  bot:
    groupId: ${VK_BOT_GROUP_ID}
    accessToken: ${VK_BOT_ACCESS_TOKEN}
