spring:
  rabbitmq:
    ready-post:
      queue: post.ready.vk
      dlq: post.ready.dlq.vk
    ad-post:
      queue: post.ad.vk
      dlq: post.ad.dlq.vk
      
    vk-bot-callback:
      queue: callback.vk.bot.current
      dlq: callback.vk.bot.dlq.current
  liquibase:
    contexts: vk-bot,data

vk:
  server:
    confirm_code: ${VK_CONFIRM_CODE}
  bot:
    groupId: ${VK_BOT_GROUP_ID}
    accessToken: ${VK_BOT_ACCESS_TOKEN}
