spring:
  rabbitmq:
    vk-parser-callback:
      queue: callback.vk.parser.current
      dlq: callback.vk.parser.dlq.current
  liquibase:
    contexts: vk-parser,data

vk:
  parser:
    callbackUrl: ${CALLBACK_URL}
    serverTitle: ${PARSER_USERNAME:GetFoodWall}
