spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgis_32_sample
    username: postgres
    password: postgres
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    ru.rassafel.foodsharing.vkbot: DEBUG

#  jpa:
#    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
#    hibernate.ddl-auto: none
