spring:
  rabbitmq:
    enabled: false
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    ready-post:
      exchange: post-ready-exchange
      storage: post.ready.storage
      queue: post.ready.vk
      dlx: post-ready-dlx
      dlq-storage: post.ready.dlq.storage
      dlq: post.ready.dlq.vk
    ad-post:
      exchange: post-ad-exchange
      storage: post.ad.storage
      queue: post.ad.vk
      dlx: post-ad-dlx
      dlq-storage: post.ad.dlq.storage
      dlq: post.ad.dlq.vk
  liquibase:
    contexts: vk-bot,data
  jpa:
    hibernate:
      ddl-auto: validate
vk:
  bot:
    confirm_code: ${VK_CONFIRM_CODE}
    groupId: ${VK_BOT_GROUP_ID}
    accessToken: ${VK_BOT_ACCESS_TOKEN}
    client:
      maxRequestQueueSize: 1000
      maxTimeForSendSomeQueries: 1000
      maxQueryCountPerTime: 20
      maxThreadCountForSendQueries: 1
      maxQuerySizeInBatch: 25
feign:
  analyzer:
    url: http://localhost:8081/

