server:
  port: ${SERVER_PORT:8040}
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    exchangeName: post-ready-exchange
    queueName: post.ready.vk

  datasource:
    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: validate

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true

  application:
    name: vk-bot

vk:
  bot:
    groupId: ${VK_BOT_GROUP_ID}
    accessToken: ${VK_BOT_ACCESS_TOKEN}
