
session-starter:
  enabled: true

vk:
  server:
    confirm_code: 88d7c1ae
  bot:
    groupId: ${VK_BOT_GROUP_ID}
    accessToken: ${VK_BOT_ACCESS_TOKEN}

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./.h2/testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: false
    change-log: classpath:init_foodsharing_db.sql
