spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgis_32_sample
    username: postgres
    password: postgres
  liquibase:
    enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    ru.rassafel.foodsharing.vkbot: DEBUG
