server:
  port: ${SERVER_PORT}
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
        health:
          enabled: true
  profiles:
    active: ${spring_profiles_active:native}
